# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
    paths:
      - 'src/assets/*'
  pull_request:
    branches: 
      - master
    types: [closed]
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.20.2]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build
      env:
        CI: true
    - name: Zip Release
      uses: TheDoctor0/zip-release@v0.3.0
      with:
        # Filename for archive
        filename: 'extension.zip'
        # Base path for archive files
        path: 'dist'
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: extension
        # Directory containing files to upload
        path: extension.zip
    - name: Chrome Addon Action
      uses: trmcnvn/chrome-addon@v2
      with:
        # ID of the extension that you are updating
        extension: ${{ secrets.EXTENSION_ID }}
        # Path to a .zip of your addon
        zip: 'extension.zip'
        # Google OAuth2 client id
        client-id: ${{ secrets.CLIENT_ID}}
        # Google OAuth2 client secret
        client-secret: ${{ secrets.CLIENT_SECRET}}
        # Google OAuth2 refresh token
        refresh-token: ${{ secrets.REFRESH_TOKEN}}
