# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
    paths:
      - 'src/assets/*'
  pull_request:
    branches: 
      - master
    types: [closed]
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.20.2]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build
      env:
        CI: true
    - name: Zip Release
      uses: TheDoctor0/zip-release@v0.3.0
      with:
        # Filename for archive
        filename: 'extension.zip'
        # Base path for archive files
        path: 'dist'
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        # Artifact name
        name: extension
        # Directory containing files to upload
        path: extension.zip
    - name: Upload to Chrome Web Store
      uses: mobilefirstllc/cws-publish@latest
      with:
        action: 'publish' # 'upload', 'publish', 'testers'から選択
        client_id: ${{secrets.CLIENT_ID}}
        client_secret: ${{secrets.CLIENT_SECRET}}
        refresh_token: ${{secrets.REFRESH_TOKEN}}
        extension_id:  ${{secrets.EXTENSION_ID }}
        zip_file: 'extension.zip'
